spring.application.name=codetracker

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}
github.redirect-uri=${GITHUB_REDIRECT_URI}

github.scope=${GITHUB_SCOPE}
github.allow-signup=${GITHUB_ALLOW_SIGNUP}
github.prompt-consent=${GITHUB_PROMPT_CONSENT}

encryption.password=${ENCRYPTION_PASSWORD}
encryption.salt=${ENCRYPTION_SALT}

jwt.secret=${JWT_SECRET}

jwt.expiration.ms=300000
refresh.token.lifetime.hour=168
device.expiration.week=12

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.maximum-pool-size=${DB_HIKARI_MAXIMUM_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${DB_HIKARI_MINIMUM_IDLE}
spring.datasource.hikari.connection-timeout=${DB_HIKARI_CONNECTION_TIMEOUT}
spring.datasource.hikari.idle-timeout=${DB_HIKARI_IDLE_TIMEOUT}
spring.datasource.hikari.max-lifetime=${DB_HIKARI_MAX_LIFETIME}

cloudinary.url=${CLOUDINARY_URL}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

app.cookie.jwt.secure=${APP_COOKIE_JWT_SECURE}
app.cookie.jwt.http-only=true
app.cookie.jwt.domain=${APP_COOKIE_DOMAIN:}
app.cookie.jwt.path=/
app.cookie.jwt.same-site=${APP_COOKIE_SAME_SITE}

app.cookie.refresh.secure=${APP_COOKIE_REFRESH_SECURE}
app.cookie.refresh.http-only=true
app.cookie.refresh.domain=${APP_COOKIE_DOMAIN:}
app.cookie.refresh.path=/
app.cookie.refresh.same-site=${APP_COOKIE_SAME_SITE}

app.cookie.device.secure=${APP_COOKIE_DEVICE_SECURE}
app.cookie.device.http-only=false
app.cookie.device.domain=${APP_COOKIE_DOMAIN:}
app.cookie.device.path=/
app.cookie.device.same-site=${APP_COOKIE_SAME_SITE}

spring.jackson.serialization.write-dates-as-timestamps=false