spring.application.name=codetracker

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}
github.redirect-uri=${GITHUB_REDIRECT_URI}

github.scope=${GITHUB_SCOPE}
github.allow-signup=${GITHUB_ALLOW_SIGNUP}
github.prompt-consent=${GITHUB_PROMPT_CONSENT}

encryption.password=${ENCRYPTION_PASSWORD}
encryption.salt=${ENCRYPTION_SALT}

jwt.secret=${JWT_SECRET}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

cloudinary.url=${CLOUDINARY_URL}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
